name: "Asciicast file to GIF"

on:
  push:
    branches:
      - "main"

jobs:
  asciicast:
    name: Asciicast to GIF
    runs-on: ubuntu-latest
    steps:
      uses: dgzlopes/asciicast-to-gif-action@v1.0
      with:
        input: porkbun-api.cast
        output: porkbun-api.gif
        theme: solarized-dark
